version: '3'

services:
  postgres:
    image: postgres:14.5-alpine
    container_name: 'java_postgres'
    ports:
      - "35100:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tink
  app:
    build: ./
    container_name: 'tink-app'
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/tink
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres
