server:
  port: ${PORT:8080}
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:35100/tink'
    username: 'user'
    password: 'password'
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/main-changelog.yaml
  springdoc:
    swagger-ui:
      path: /moi-swagger.html
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
storage:
  location: D:\files
cors:
  allowed-origin: http://localhost:3000