server:
  port: ${PORT:8080}
spring:
  datasource:
    url: 'jdbc:postgresql://localhost:35100/tink'
    username: 'user'
    password: 'password'
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
        format_sql: true
  liquibase:
    change-log: classpath:/db/changelog/main-changelog.xml
  springdoc:
    swagger-ui:
      path: /moi-swagger.html
